-- Expanded Common Items Seed Data

insert into common_items (name, category_name, default_unit, icon) values

-- Produce (Fruit)
('Grapes', 'Produce', 'kg', '🍇'),
('Melon', 'Produce', 'pcs', '🍈'),
('Watermelon', 'Produce', 'pcs', '🍉'),
('Orange', 'Produce', 'kg', '🍊'),
('Mandarin', 'Produce', 'kg', '🍊'),
('Pear', 'Produce', 'kg', '🍐'),
('Peach', 'Produce', 'kg', '🍑'),
('Cherries', 'Produce', 'kg', '🍒'),
('Strawberry', 'Produce', 'pack', '🍓'),
('Blueberry', 'Produce', 'pack', '🫐'),
('Kiwi', 'Produce', 'pcs', '🥝'),
('Mango', 'Produce', 'pcs', '🥭'),
('Pineapple', 'Produce', 'pcs', '🍍'),
('Coconut', 'Produce', 'pcs', '🥥'),
('Plum', 'Produce', 'kg', '🫐'),
('Apricot', 'Produce', 'kg', '🍑'),
('Raspberry', 'Produce', 'pack', '🫐'),
('Blackberry', 'Produce', 'pack', '🫐'),
('Pomegranate', 'Produce', 'pcs', '🫐'),
('Lime', 'Produce', 'pcs', '🍋'),
('Grapefruit', 'Produce', 'pcs', '🍊'),

-- Produce (Vegetables)
('Bell Pepper', 'Produce', 'pcs', '🫑'),
('Chili Pepper', 'Produce', 'pcs', '🌶️'),
('Corn', 'Produce', 'pcs', '🌽'),
('Spinach', 'Produce', 'bag', '🥬'),
('Kale', 'Produce', 'bag', '🥬'),
('Broccoli', 'Produce', 'pcs', '🥦'),
('Cauliflower', 'Produce', 'pcs', '🥦'),
('Mushrooms', 'Produce', 'pack', '🍄'),
('Eggplant', 'Produce', 'pcs', '🍆'),
('Zucchini', 'Produce', 'pcs', '🥒'),
('Sweet Potato', 'Produce', 'kg', '🥔'),
('Pumpkin', 'Produce', 'pcs', '🎃'),
('Radish', 'Produce', 'pack', '🥗'),
('Asparagus', 'Produce', 'pack', '🥬'),
('Green Beans', 'Produce', 'kg', '🥬'),
('Peas', 'Produce', 'bag', '🫛'),
('Cabbage', 'Produce', 'pcs', '🥬'),
('Brussels Sprouts', 'Produce', 'bag', '🥬'),
('Celery', 'Produce', 'pcs', '🥬'),
('Ginger', 'Produce', 'g', '🫚'),
('Fresh Herbs', 'Produce', 'pack', '🌿'),
('Basil', 'Produce', 'pack', '🌿'),
('Cilantro', 'Produce', 'pack', '🌿'),
('Parsley', 'Produce', 'pack', '🌿'),
('Mint', 'Produce', 'pack', '🌿'),

-- Dairy & Alternative
('Mozzarella', 'Dairy & Cheese', 'pack', '🧀'),
('Cheddar', 'Dairy & Cheese', 'pack', '🧀'),
('Parmesan', 'Dairy & Cheese', 'pack', '🧀'),
('Feta', 'Dairy & Cheese', 'pack', '🧀'),
('Gouda', 'Dairy & Cheese', 'pack', '🧀'),
('Brie', 'Dairy & Cheese', 'pack', '🧀'),
('Almond Milk', 'Dairy & Cheese', 'l', '🥛'),
('Oat Milk', 'Dairy & Cheese', 'l', '🥛'),
('Soy Milk', 'Dairy & Cheese', 'l', '🥛'),
('Sour Cream', 'Dairy & Cheese', 'pack', '🥣'),
('Cottage Cheese', 'Dairy & Cheese', 'pack', '🥣'),
('Whipping Cream', 'Dairy & Cheese', 'ml', '🥛'),
('Greek Yogurt', 'Dairy & Cheese', 'pack', '🥣'),
('Ice Cream', 'Dairy & Cheese', 'pack', '🍦'), -- Or Frozen?

-- Meat & Fish
('Steak', 'Meat & Fish', 'kg', '🥩'),
('Pork Chop', 'Meat & Fish', 'kg', '🥩'),
('Lamb', 'Meat & Fish', 'kg', '🥩'),
('Turkey', 'Meat & Fish', 'kg', '🦃'),
('Whole Chicken', 'Meat & Fish', 'pcs', '🍗'),
('Chicken Wings', 'Meat & Fish', 'kg', '🍗'),
('Chicken Thighs', 'Meat & Fish', 'kg', '🍗'),
('Tuna (Fresh)', 'Meat & Fish', 'kg', '🐟'),
('Cod', 'Meat & Fish', 'kg', '🐟'),
('Shrimp', 'Meat & Fish', 'bag', '🦐'),
('Crab', 'Meat & Fish', 'pcs', '🦀'),
('Lobster', 'Meat & Fish', 'pcs', '🦞'),
('Oysters', 'Meat & Fish', 'pcs', '🦪'),
('Ham', 'Meat & Fish', 'pack', '🍖'),
('Salami', 'Meat & Fish', 'pack', '🍖'),
('Pepperoni', 'Meat & Fish', 'pack', '🍕'),

-- Pantry
('Beans (Canned)', 'Pantry & Dry Goods', 'can', '🥫'),
('Lentils', 'Pantry & Dry Goods', 'pack', '🫘'),
('Chickpeas', 'Pantry & Dry Goods', 'can', '🫘'),
('Quinoa', 'Pantry & Dry Goods', 'pack', '🌾'),
('Oats', 'Pantry & Dry Goods', 'pack', '🌾'),
('Granola', 'Pantry & Dry Goods', 'pack', '🥣'),
('Peanut Butter', 'Pantry & Dry Goods', 'jar', '🥜'),
('Jam', 'Pantry & Dry Goods', 'jar', '🍓'),
('Honey', 'Pantry & Dry Goods', 'jar', '🍯'),
('Maple Syrup', 'Pantry & Dry Goods', 'bottle', '🍁'),
('Vinegar', 'Pantry & Dry Goods', 'bottle', '🍾'),
('Soy Sauce', 'Pantry & Dry Goods', 'bottle', '🥢'),
('Hot Sauce', 'Pantry & Dry Goods', 'bottle', '🌶️'),
('Mayonnaise', 'Pantry & Dry Goods', 'jar', '🥚'),
('Ketchup', 'Pantry & Dry Goods', 'bottle', '🍅'),
('Mustard', 'Pantry & Dry Goods', 'bottle', '🌭'),
('BBQ Sauce', 'Pantry & Dry Goods', 'bottle', '🍖'),
('Spices', 'Pantry & Dry Goods', 'jar', '🧂'),
('Pepper', 'Pantry & Dry Goods', 'g', '🧂'),
('Cinnamon', 'Pantry & Dry Goods', 'g', '🧂'),
('Vanilla Extract', 'Pantry & Dry Goods', 'bottle', '🍦'),
('Baking Powder', 'Pantry & Dry Goods', 'pack', '🎂'),
('Yeast', 'Pantry & Dry Goods', 'pack', '🍞'),
('Chocolate Chips', 'Pantry & Dry Goods', 'pack', '🍪'),
('Soup (Canned)', 'Pantry & Dry Goods', 'can', '🥣'),
('Tuna (Canned)', 'Pantry & Dry Goods', 'can', '🐟'),
('Noodles', 'Pantry & Dry Goods', 'pack', '🍜'),

-- Frozen
('Frozen Pizza', 'Frozen', 'pcs', '🍕'),
('Frozen Peas', 'Frozen', 'bag', '❄️'),
('Frozen Berries', 'Frozen', 'bag', '🍓'),
('Frozen Fries', 'Frozen', 'bag', '🍟'),
('Ice Cubes', 'Frozen', 'bag', '🧊'),

-- Beverages
('Tea Bags', 'Beverages', 'box', '🍵'),
('Energy Drink', 'Beverages', 'can', '⚡'),
('Iced Tea', 'Beverages', 'bottle', '🍹'),
('Sparkling Water', 'Beverages', 'bottle', '🫧'),
('Smoothie', 'Beverages', 'bottle', '🥤'),

-- Snacks
('Popcorn', 'Snacks', 'bag', '🍿'),
('Pretzels', 'Snacks', 'bag', '🥨'),
('Crackers', 'Snacks', 'box', '🍘'),
('Candy', 'Snacks', 'pack', '🍬'),
('Gum', 'Snacks', 'pack', '🍬'),
('Dried Fruit', 'Snacks', 'pack', '🥭'),

-- Personal Care
('Soap', 'Personal Care', 'pcs', '🧼'),
('Body Wash', 'Personal Care', 'bottle', '🚿'),
('Conditioner', 'Personal Care', 'bottle', '🧴'),
('Deodorant', 'Personal Care', 'pcs', '👃'),
('Razor', 'Personal Care', 'pack', '🪒'),
('Shaving Cream', 'Personal Care', 'can', '🪒'),
('Lotion', 'Personal Care', 'bottle', '🧴'),
('Sunscreen', 'Personal Care', 'bottle', '☀️'),
('Floss', 'Personal Care', 'pack', '🦷'),

-- Household
('Insects Spray', 'Household & Cleaning', 'can', '🪳'),
('Light Bulbs', 'Household & Cleaning', 'pack', '💡'),
('Batteries', 'Household & Cleaning', 'pack', '🔋'),
('Sponge', 'Household & Cleaning', 'pack', '🧽'),
('Bleach', 'Household & Cleaning', 'bottle', '🧪'),
('Glass Cleaner', 'Household & Cleaning', 'bottle', '🪟'),
('Foil', 'Household & Cleaning', 'roll', '🥈'),
('Plastic Wrap', 'Household & Cleaning', 'roll', '🌯'),
('Napkins', 'Household & Cleaning', 'pack', '🤧'),
('Tissues', 'Household & Cleaning', 'box', '🤧'),

-- Vegetarian & Vegan
('Tofu (Firm)', 'Produce', 'pack', '🧊'), 
('Tofu (Silken)', 'Produce', 'pack', '🧊'),
('Tempeh', 'Produce', 'pack', '🫘'),
('Seitan', 'Produce', 'pack', '🌾'),
('Veggie Burger', 'Meat & Fish', 'pack', '🍔'),
('Hummus', 'Dairy & Cheese', 'pack', '🥙'),
('Falafel', 'Produce', 'pack', '🧆'),
('Soy Mince', 'Pantry & Dry Goods', 'pack', '🫘'),
('Nutritional Yeast', 'Pantry & Dry Goods', 'pack', '🧀')

on conflict (name) do nothing;
