-- Complete Setup for Common Items with Bilingual Support (EN/DE)

-- 1. Create Items Table (if not exists)
create table if not exists common_items (
  id uuid default gen_random_uuid() primary key,
  name text not null unique, -- English Name (Unique Constraint)
  name_de text,              -- German Name
  category_name text not null,
  default_unit text default 'units',
  icon text,
  created_at timestamp with time zone default now()
);

-- 2. Add Index for German Search
create index if not exists common_items_name_de_idx on common_items (name_de);

-- 3. RLS
alter table common_items enable row level security;
drop policy if exists "Common items are public" on common_items;
create policy "Common items are public" on common_items for select using (true);

-- 4. Seed Data (Upsert)
insert into common_items (name, name_de, category_name, default_unit, icon) values
-- Dairy & Alternatives
('Milk', 'Milch', 'Dairy & Cheese', 'l', '🥛'),
('Cheese', 'Käse', 'Dairy & Cheese', 'kg', '🧀'),
('Butter', 'Butter', 'Dairy & Cheese', 'g', '🧈'),
('Yogurt', 'Joghurt', 'Dairy & Cheese', 'g', '🥣'),
('Cream', 'Sahne', 'Dairy & Cheese', 'ml', '🥛'),
('Eggs', 'Eier', 'Dairy & Cheese', 'pcs', '🥚'),
('Mozzarella', 'Mozzarella', 'Dairy & Cheese', 'pack', '🧀'),
('Cheddar', 'Cheddar', 'Dairy & Cheese', 'pack', '🧀'),
('Parmesan', 'Parmesan', 'Dairy & Cheese', 'pack', '🧀'),
('Feta', 'Feta', 'Dairy & Cheese', 'pack', '🧀'),
('Gouda', 'Gouda', 'Dairy & Cheese', 'pack', '🧀'),
('Brie', 'Brie', 'Dairy & Cheese', 'pack', '🧀'),
('Almond Milk', 'Mandelmilch', 'Dairy & Cheese', 'l', '🥛'),
('Oat Milk', 'Hafermilch', 'Dairy & Cheese', 'l', '🥛'),
('Soy Milk', 'Sojamilch', 'Dairy & Cheese', 'l', '🥛'),
('Sour Cream', 'Sauerrahm', 'Dairy & Cheese', 'pack', '🥣'),
('Cottage Cheese', 'Hüttenkäse', 'Dairy & Cheese', 'pack', '🥣'),
('Whipping Cream', 'Schlagsahne', 'Dairy & Cheese', 'ml', '🥛'),
('Greek Yogurt', 'Griechischer Joghurt', 'Dairy & Cheese', 'pack', '🥣'),
('Ice Cream', 'Eiscreme', 'Dairy & Cheese', 'pack', '🍦'),

-- Produce (Fruits)
('Bananas', 'Bananen', 'Produce', 'kg', '🍌'),
('Apples', 'Äpfel', 'Produce', 'kg', '🍎'),
('Tomatoes', 'Tomaten', 'Produce', 'kg', '🍅'),
('Lemons', 'Zitronen', 'Produce', 'pcs', '🍋'),
('Limes', 'Limetten', 'Produce', 'pcs', '🍋'),
('Grapes', 'Trauben', 'Produce', 'kg', '🍇'),
('Melon', 'Melone', 'Produce', 'pcs', '🍈'),
('Watermelon', 'Wassermelone', 'Produce', 'pcs', '🍉'),
('Oranges', 'Orangen', 'Produce', 'kg', '🍊'),
('Mandarins', 'Mandarinen', 'Produce', 'kg', '🍊'),
('Pears', 'Birnen', 'Produce', 'kg', '🍐'),
('Peaches', 'Pfirsiche', 'Produce', 'kg', '🍑'),
('Cherries', 'Kirschen', 'Produce', 'kg', '🍒'),
('Strawberries', 'Erdbeeren', 'Produce', 'pack', '🍓'),
('Blueberries', 'Blaubeeren', 'Produce', 'pack', '🫐'),
('Kiwis', 'Kiwis', 'Produce', 'pcs', '🥝'),
('Mango', 'Mango', 'Produce', 'pcs', '🥭'),
('Pineapple', 'Ananas', 'Produce', 'pcs', '🍍'),
('Coconut', 'Kokosnuss', 'Produce', 'pcs', '🥥'),
('Plums', 'Pflaumen', 'Produce', 'kg', '🫐'),
('Apricots', 'Aprikosen', 'Produce', 'kg', '🍑'),
('Raspberries', 'Himbeeren', 'Produce', 'pack', '🫐'),
('Blackberries', 'Brombeeren', 'Produce', 'pack', '🫐'),
('Pomegranate', 'Granatapfel', 'Produce', 'pcs', '🫐'),
('Grapefruit', 'Grapefruit', 'Produce', 'pcs', '🍊'),
('Avocado', 'Avocado', 'Produce', 'pcs', '🥑'),

-- Produce (Vegetables)
('Potatoes', 'Kartoffeln', 'Produce', 'kg', '🥔'),
('Onions', 'Zwiebeln', 'Produce', 'kg', '🧅'),
('Carrots', 'Karotten', 'Produce', 'kg', '🥕'),
('Lettuce', 'Salat', 'Produce', 'pcs', '🥬'),
('Cucumber', 'Gurke', 'Produce', 'pcs', '🥒'),
('Garlic', 'Knoblauch', 'Produce', 'pcs', '🧄'),
('Bell Pepper', 'Paprika', 'Produce', 'pcs', '🫑'),
('Chili Pepper', 'Chili', 'Produce', 'pcs', '🌶️'),
('Corn', 'Mais', 'Produce', 'pcs', '🌽'),
('Spinach', 'Spinat', 'Produce', 'bag', '🥬'),
('Kale', 'Grünkohl', 'Produce', 'bag', '🥬'),
('Broccoli', 'Brokkoli', 'Produce', 'pcs', '🥦'),
('Cauliflower', 'Blumenkohl', 'Produce', 'pcs', '🥦'),
('Mushrooms', 'Pilze', 'Produce', 'pack', '🍄'),
('Eggplant', 'Aubergine', 'Produce', 'pcs', '🍆'),
('Zucchini', 'Zucchini', 'Produce', 'pcs', '🥒'),
('Sweet Potato', 'Süßkartoffel', 'Produce', 'kg', '🥔'),
('Pumpkin', 'Kürbis', 'Produce', 'pcs', '🎃'),
('Radish', 'Radieschen', 'Produce', 'pack', '🥗'),
('Asparagus', 'Spargel', 'Produce', 'pack', '🥬'),
('Green Beans', 'Grüne Bohnen', 'Produce', 'kg', '🥬'),
('Peas', 'Erbsen', 'Produce', 'bag', '🫛'),
('Cabbage', 'Kohl', 'Produce', 'pcs', '🥬'),
('Brussels Sprouts', 'Rosenkohl', 'Produce', 'bag', '🥬'),
('Celery', 'Staudensellerie', 'Produce', 'pcs', '🥬'),
('Ginger', 'Ingwer', 'Produce', 'g', '🫚'),
('Fresh Herbs', 'Frische Kräuter', 'Produce', 'pack', '🌿'),
('Basil', 'Basilikum', 'Produce', 'pack', '🌿'),
('Cilantro', 'Koriander', 'Produce', 'pack', '🌿'),
('Parsley', 'Petersilie', 'Produce', 'pack', '🌿'),
('Mint', 'Minze', 'Produce', 'pack', '🌿'),

-- Meat & Fish
('Chicken Breast', 'Hähnchenbrust', 'Meat & Fish', 'kg', '🍗'),
('Ground Beef', 'Hackfleisch', 'Meat & Fish', 'kg', '🥩'),
('Salmon', 'Lachs', 'Meat & Fish', 'kg', '🐟'),
('Bacon', 'Speck', 'Meat & Fish', 'g', '🥓'),
('Sausages', 'Würstchen', 'Meat & Fish', 'pcs', '🌭'),
('Steak', 'Steak', 'Meat & Fish', 'kg', '🥩'),
('Pork Chop', 'Kotelett', 'Meat & Fish', 'kg', '🥩'),
('Lamb', 'Lamm', 'Meat & Fish', 'kg', '🥩'),
('Turkey', 'Pute', 'Meat & Fish', 'kg', '🦃'),
('Whole Chicken', 'Ganzes Hähnchen', 'Meat & Fish', 'pcs', '🍗'),
('Chicken Wings', 'Hähnchenflügel', 'Meat & Fish', 'kg', '🍗'),
('Chicken Thighs', 'Hähnchenschenkel', 'Meat & Fish', 'kg', '🍗'),
('Tuna (Fresh)', 'Thunfisch (Frisch)', 'Meat & Fish', 'kg', '🐟'),
('Cod', 'Kabeljau', 'Meat & Fish', 'kg', '🐟'),
('Shrimp', 'Garnelen', 'Meat & Fish', 'bag', '🦐'),
('Crab', 'Krabben', 'Meat & Fish', 'pcs', '🦀'),
('Lobster', 'Hummer', 'Meat & Fish', 'pcs', '🦞'),
('Oysters', 'Austern', 'Meat & Fish', 'pcs', '🦪'),
('Ham', 'Schinken', 'Meat & Fish', 'pack', '🍖'),
('Salami', 'Salami', 'Meat & Fish', 'pack', '🍖'),
('Pepperoni', 'Peperoniwurst', 'Meat & Fish', 'pack', '🍕'),

-- Vegetarian & Vegan
('Tofu (Firm)', 'Tofu (Natur)', 'Produce', 'pack', '🧊'), 
('Tofu (Silken)', 'Seidentofu', 'Produce', 'pack', '🧊'),
('Tempeh', 'Tempeh', 'Produce', 'pack', '🫘'),
('Seitan', 'Seitan', 'Produce', 'pack', '🌾'),
('Veggie Burger', 'Veggie Burger', 'Meat & Fish', 'pack', '🍔'),
('Hummus', 'Hummus', 'Dairy & Cheese', 'pack', '🥙'),
('Falafel', 'Falafel', 'Produce', 'pack', '🧆'),
('Soy Mince', 'Soja Hack', 'Pantry & Dry Goods', 'pack', '🫘'),
('Nutritional Yeast', 'Hefeflocken', 'Pantry & Dry Goods', 'pack', '🧀'),

-- Bakery
('Bread', 'Brot', 'Bakery', 'pcs', '🍞'),
('Toast', 'Toast', 'Bakery', 'pcs', '🍞'),
('Croissant', 'Croissant', 'Bakery', 'pcs', '🥐'),
('Bagels', 'Bagels', 'Bakery', 'pcs', '🥯'),

-- Pantry
('Rice', 'Reis', 'Pantry & Dry Goods', 'kg', '🍚'),
('Pasta', 'Nudeln', 'Pantry & Dry Goods', 'kg', '🍝'),
('Flour', 'Mehl', 'Pantry & Dry Goods', 'kg', '🥡'),
('Sugar', 'Zucker', 'Pantry & Dry Goods', 'kg', '🧂'),
('Salt', 'Salz', 'Pantry & Dry Goods', 'g', '🧂'),
('Olive Oil', 'Olivenöl', 'Pantry & Dry Goods', 'l', '🫒'),
('Cereal', 'Müsli', 'Pantry & Dry Goods', 'box', '🥣'),
('Tomato Sauce', 'Tomatensauce', 'Pantry & Dry Goods', 'jar', '🥫'),
('Coffee', 'Kaffee', 'Pantry & Dry Goods', 'g', '☕'),
('Tea', 'Tee', 'Pantry & Dry Goods', 'box', '🍵'),
('Beans (Canned)', 'Bohnen (Dose)', 'Pantry & Dry Goods', 'can', '🥫'),
('Lentils', 'Linsen', 'Pantry & Dry Goods', 'pack', '🫘'),
('Chickpeas', 'Kichererbsen', 'Pantry & Dry Goods', 'can', '🫘'),
('Quinoa', 'Quinoa', 'Pantry & Dry Goods', 'pack', '🌾'),
('Oats', 'Haferflocken', 'Pantry & Dry Goods', 'pack', '🌾'),
('Granola', 'Knuspermüsli', 'Pantry & Dry Goods', 'pack', '🥣'),
('Peanut Butter', 'Erdnussbutter', 'Pantry & Dry Goods', 'jar', '🥜'),
('Jam', 'Marmelade', 'Pantry & Dry Goods', 'jar', '🍓'),
('Honey', 'Honig', 'Pantry & Dry Goods', 'jar', '🍯'),
('Maple Syrup', 'Ahornsirup', 'Pantry & Dry Goods', 'bottle', '🍁'),
('Vinegar', 'Essig', 'Pantry & Dry Goods', 'bottle', '🍾'),
('Soy Sauce', 'Sojasauce', 'Pantry & Dry Goods', 'bottle', '🥢'),
('Hot Sauce', 'Scharfe Sauce', 'Pantry & Dry Goods', 'bottle', '🌶️'),
('Mayonnaise', 'Mayonnaise', 'Pantry & Dry Goods', 'jar', '🥚'),
('Ketchup', 'Ketchup', 'Pantry & Dry Goods', 'bottle', '🍅'),
('Mustard', 'Senf', 'Pantry & Dry Goods', 'bottle', '🌭'),
('BBQ Sauce', 'BBQ Sauce', 'Pantry & Dry Goods', 'bottle', '🍖'),
('Spices', 'Gewürze', 'Pantry & Dry Goods', 'jar', '🧂'),
('Pepper', 'Pfeffer', 'Pantry & Dry Goods', 'g', '🧂'),
('Cinnamon', 'Zimt', 'Pantry & Dry Goods', 'g', '🧂'),
('Vanilla Extract', 'Vanilleextrakt', 'Pantry & Dry Goods', 'bottle', '🍦'),
('Baking Powder', 'Backpulver', 'Pantry & Dry Goods', 'pack', '🎂'),
('Yeast', 'Hefe', 'Pantry & Dry Goods', 'pack', '🍞'),
('Chocolate Chips', 'Schokostreusel', 'Pantry & Dry Goods', 'pack', '🍪'),
('Soup (Canned)', 'Suppe (Dose)', 'Pantry & Dry Goods', 'can', '🥣'),
('Tuna (Canned)', 'Thunfisch (Dose)', 'Pantry & Dry Goods', 'can', '🐟'),
('Noodles', 'Instant Nudeln', 'Pantry & Dry Goods', 'pack', '🍜'),

-- Snacks
('Chips', 'Chips', 'Snacks', 'bag', '🍟'),
('Chocolate', 'Schokolade', 'Snacks', 'g', '🍫'),
('Cookies', 'Kekse', 'Snacks', 'pack', '🍪'),
('Nuts', 'Nüsse', 'Snacks', 'g', '🥜'),
('Popcorn', 'Popcorn', 'Snacks', 'bag', '🍿'),
('Pretzels', 'Brezeln', 'Snacks', 'bag', '🥨'),
('Crackers', 'Cracker', 'Snacks', 'box', '🍘'),
('Candy', 'Süßigkeiten', 'Snacks', 'pack', '🍬'),
('Gum', 'Kaugummi', 'Snacks', 'pack', '🍬'),
('Dried Fruit', 'Trockenobst', 'Snacks', 'pack', '🥭'),

-- Beverages
('Water', 'Wasser', 'Beverages', 'l', '💧'),
('Juice', 'Saft', 'Beverages', 'l', '🧃'),
('Soda', 'Limo', 'Beverages', 'can', '🥤'),
('Beer', 'Bier', 'Beverages', 'bottle', '🍺'),
('Wine', 'Wein', 'Beverages', 'bottle', '🍷'),
('Tea Bags', 'Teebeutel', 'Beverages', 'box', '🍵'),
('Energy Drink', 'Energy Drink', 'Beverages', 'can', '⚡'),
('Iced Tea', 'Eistee', 'Beverages', 'bottle', '🍹'),
('Sparkling Water', 'Sprudelwasser', 'Beverages', 'bottle', '🫧'),
('Smoothie', 'Smoothie', 'Beverages', 'bottle', '🥤'),

-- Frozen
('Frozen Pizza', 'Tiefkühlpizza', 'Frozen', 'pcs', '🍕'),
('Frozen Peas', 'TK Erbsen', 'Frozen', 'bag', '❄️'),
('Frozen Berries', 'TK Beeren', 'Frozen', 'bag', '🍓'),
('Frozen Fries', 'Pommes Frites', 'Frozen', 'bag', '🍟'),
('Ice Cubes', 'Eiswürfel', 'Frozen', 'bag', '🧊'),

-- Household
('Toilet Paper', 'Toilettenpapier', 'Household & Cleaning', 'pack', '🧻'),
('Paper Towels', 'Küchenrolle', 'Household & Cleaning', 'roll', '🧻'),
('Dish Soap', 'Spülmittel', 'Household & Cleaning', 'bottle', '🧼'),
('Laundry Detergent', 'Waschmittel', 'Household & Cleaning', 'bottle', '🧺'),
('Trash Bags', 'Müllbeutel', 'Household & Cleaning', 'box', '🗑️'),
('Insects Spray', 'Insektenspray', 'Household & Cleaning', 'can', '🪳'),
('Light Bulbs', 'Glühbirnen', 'Household & Cleaning', 'pack', '💡'),
('Batteries', 'Batterien', 'Household & Cleaning', 'pack', '🔋'),
('Sponge', 'Schwamm', 'Household & Cleaning', 'pack', '🧽'),
('Bleach', 'Bleichmittel', 'Household & Cleaning', 'bottle', '🧪'),
('Glass Cleaner', 'Glasreiniger', 'Household & Cleaning', 'bottle', '🪟'),
('Foil', 'Alufolie', 'Household & Cleaning', 'roll', '🥈'),
('Plastic Wrap', 'Frischhaltefolie', 'Household & Cleaning', 'roll', '🌯'),
('Napkins', 'Servietten', 'Household & Cleaning', 'pack', '🤧'),
('Tissues', 'Taschentücher', 'Household & Cleaning', 'box', '🤧'),

-- Personal Care
('Toothpaste', 'Zahnpasta', 'Personal Care', 'tube', '🦷'),
('Shampoo', 'Shampoo', 'Personal Care', 'bottle', '🧴'),
('Soap', 'Seife', 'Personal Care', 'pcs', '🧼'),
('Body Wash', 'Duschgel', 'Personal Care', 'bottle', '🚿'),
('Conditioner', 'Spülung', 'Personal Care', 'bottle', '🧴'),
('Deodorant', 'Deo', 'Personal Care', 'pcs', '👃'),
('Razor', 'Rasierer', 'Personal Care', 'pack', '🪒'),
('Shaving Cream', 'Rasierschaum', 'Personal Care', 'can', '🪒'),
('Lotion', 'Creme', 'Personal Care', 'bottle', '🧴'),
('Sunscreen', 'Sonnencreme', 'Personal Care', 'bottle', '☀️'),
('Floss', 'Zahnseide', 'Personal Care', 'pack', '🦷')

on conflict (name) do update 
  set name_de = excluded.name_de, 
      category_name = excluded.category_name,
      default_unit = excluded.default_unit,
      icon = excluded.icon;
